"use client";

import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import ReactMarkdown from "react-markdown";

type Language = "english" | "afrikaans";

interface ActionItem {
  id: string;
  text: string;
  assignee: string | null;
  done: boolean;
}

interface Meeting {
  id: string;
  title: string;
  date: string;
  transcript: string | null;
  minutes: string | null;
  language: string;
  actionItems: ActionItem[];
}

const labels = (lang: Language) => ({
  date:  lang === "afrikaans" ? "DATUM"        : "DATE",
  time:  lang === "afrikaans" ? "TYD"          : "TIME",
  att:   lang === "afrikaans" ? "TEENWOORDIG"  : "ATTENDEES",
  tasks: lang === "afrikaans" ? "Aksie-items"  : "Action Items",
  chair: lang === "afrikaans" ? "VOORSITTER HANDTEKENING" : "CHAIRPERSON SIGNATURE",
  appr:  lang === "afrikaans" ? "DATUM GOEDGEKEUR"        : "DATE APPROVED",
  official: lang === "afrikaans" ? "Amptelike Vergaderingnotules" : "Official Meeting Minutes",
});

export default function ExportPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();

  const [meeting, setMeeting] = useState<Meeting | null>(null);
  const [language, setLanguage] = useState<Language>("english");
  const [emailTo, setEmailTo] = useState("");
  const [showPrintPreview, setShowPrintPreview] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetch(`/api/meetings/${id}`)
      .then((r) => r.json())
      .then((data: Meeting) => {
        setMeeting(data);
        setLanguage((data.language === "afrikaans" ? "afrikaans" : "english") as Language);
      });
  }, [id]);

  if (!meeting) {
    return <div className="min-h-screen bg-gray-950 flex items-center justify-center text-gray-400">Loading…</div>;
  }

  const L = labels(language);
  const dateStr = new Date(meeting.date).toLocaleDateString("en-ZA", {
    day: "2-digit", month: "long", year: "numeric",
  });
  const timeStr = new Date(meeting.date).toLocaleTimeString("en-ZA", {
    hour: "2-digit", minute: "2-digit",
  });

  const taskLines = meeting.actionItems.length
    ? meeting.actionItems.map((t) => `[${t.done ? "✓" : " "}] ${t.text}${t.assignee ? ` (${t.assignee})` : ""}`).join("\n")
    : language === "afrikaans" ? "Geen aksie-items nie." : "No action items recorded.";

  const emailBody = [
    `${language === "afrikaans" ? "VERGADERINGNOTULE" : "MEETING MINUTES"} — ${meeting.title}`,
    `${L.date}: ${dateStr}`,
    "",
    meeting.minutes ?? (language === "afrikaans" ? "Geen notule gegenereer nie." : "No minutes generated."),
    "",
    `${L.tasks}:`,
    taskLines,
    "",
    "---",
    "Generated by DAB Meetings",
  ].join("\n");

  const handleWordExport = () => {
    if (!meeting.minutes) return;

    const taskHtml = meeting.actionItems.length
      ? meeting.actionItems
          .map((t) => `<li>[${t.done ? "X" : " "}] ${t.text}${t.assignee ? ` (${t.assignee})` : ""}</li>`)
          .join("")
      : "<li>No action items recorded.</li>";

    // Simple markdown → basic HTML (headings + paragraphs)
    const content = meeting.minutes
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/^/, "<p>")
      .replace(/$/, "</p>");

    const html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset='utf-8'><title>${meeting.title}</title>
<style>
  body{font-family:Calibri,Arial,sans-serif;line-height:1.5;color:#333;}
  h1{color:#1a1a6e;font-size:24pt;border-bottom:2px solid #1a1a6e;padding-bottom:5px;}
  h2{color:#2563eb;font-size:16pt;margin-top:20pt;}
  table{width:100%;border-collapse:collapse;margin-bottom:20pt;}
  td{padding:8pt;font-size:10pt;border:1px solid #e2e8f0;}
  .label{font-weight:bold;color:#1a1a6e;width:100pt;}
  .footer{font-size:9pt;color:#94a3b8;text-align:center;margin-top:40pt;border-top:1px solid #eee;padding-top:10pt;}
</style></head>
<body>
<h1>${meeting.title}</h1>
<p><em>${L.official}</em></p>
<table>
  <tr><td class="label">${L.date}</td><td>${dateStr} ${timeStr}</td></tr>
  <tr><td class="label">${L.tasks}</td><td>${meeting.actionItems.length} items</td></tr>
</table>
<div>${content}</div>
<h2>${L.tasks}</h2>
<ul>${taskHtml}</ul>
<div class="footer">Generated by DAB Meetings — ${dateStr}</div>
</body></html>`;

    const blob = new Blob(["\ufeff", html], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${meeting.title.replace(/\s+/g, "_")}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    setShowPrintPreview(true);
    setTimeout(() => window.print(), 300);
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`${language === "afrikaans" ? "Vergaderingnotule" : "Meeting Minutes"} — ${meeting.title}`);
    const body = encodeURIComponent(emailBody);
    window.location.href = `mailto:${emailTo}?subject=${subject}&body=${body}`;
  };

  return (
    <>
      {/* Print preview — only visible when printing */}
      {showPrintPreview && (
        <div ref={printRef} className="hidden print:block p-10 font-sans text-black bg-white">
          <div className="flex justify-between items-start border-b-2 border-gray-900 pb-5 mb-6">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{meeting.title}</h1>
              <p className="text-blue-700 text-sm font-semibold mt-1">{L.official}</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 bg-gray-50 border border-gray-200 p-4 rounded mb-6 text-sm">
            <div><strong>{L.date}:</strong> {dateStr}</div>
            <div><strong>{L.time}:</strong> {timeStr}</div>
          </div>
          <div className="prose prose-sm max-w-none text-gray-800 leading-relaxed mb-8">
            {meeting.minutes?.split("\n").map((line, i) => <p key={i}>{line}</p>)}
          </div>
          {meeting.actionItems.length > 0 && (
            <>
              <h2 className="font-bold text-gray-900 mb-3">{L.tasks}</h2>
              <ul className="text-sm space-y-1">
                {meeting.actionItems.map((t) => (
                  <li key={t.id}>[{t.done ? "✓" : " "}] {t.text}{t.assignee && ` — ${t.assignee}`}</li>
                ))}
              </ul>
            </>
          )}
          <div className="grid grid-cols-2 gap-12 mt-16 border-t pt-4 text-xs font-bold text-gray-700">
            <div>{L.chair}</div>
            <div>{L.appr}</div>
          </div>
        </div>
      )}

      {/* Normal UI */}
      <div className="min-h-screen bg-gray-950 text-white print:hidden">
        <header className="flex items-center gap-3 px-8 py-4 border-b border-gray-800">
          <button onClick={() => router.back()} className="text-gray-400 hover:text-white text-sm transition">
            ←
          </button>
          <h1 className="text-xl font-bold">Export — {meeting.title}</h1>
        </header>

        <main className="max-w-2xl mx-auto px-8 py-8 space-y-6">
          {/* Language */}
          <div className="flex items-center gap-3">
            <span className="text-sm text-gray-400">Output language:</span>
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value as Language)}
              className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-1.5 text-sm text-white"
            >
              <option value="english">English</option>
              <option value="afrikaans">Afrikaans</option>
            </select>
          </div>

          {/* Export options */}
          <div className="space-y-3">
            {/* PDF */}
            <div className="bg-gray-900 rounded-xl p-5 border border-gray-800 flex items-center justify-between">
              <div>
                <p className="font-medium">PDF</p>
                <p className="text-xs text-gray-500 mt-0.5">Print to PDF via browser dialog</p>
              </div>
              <button
                onClick={handlePrint}
                disabled={!meeting.minutes}
                className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:opacity-40 text-sm font-medium transition"
              >
                Print / Save PDF
              </button>
            </div>

            {/* Word */}
            <div className="bg-gray-900 rounded-xl p-5 border border-gray-800 flex items-center justify-between">
              <div>
                <p className="font-medium">Word Document</p>
                <p className="text-xs text-gray-500 mt-0.5">Download as .doc file</p>
              </div>
              <button
                onClick={handleWordExport}
                disabled={!meeting.minutes}
                className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 disabled:opacity-40 text-sm font-medium transition"
              >
                Download .doc
              </button>
            </div>

            {/* Email */}
            <div className="bg-gray-900 rounded-xl p-5 border border-gray-800 space-y-3">
              <div>
                <p className="font-medium">Email</p>
                <p className="text-xs text-gray-500 mt-0.5">Open in your default email client</p>
              </div>
              <input
                type="email"
                placeholder="Recipient email (optional)"
                value={emailTo}
                onChange={(e) => setEmailTo(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-blue-500"
              />
              <div className="flex gap-2">
                <button
                  onClick={handleEmail}
                  className="flex-1 py-2 rounded-lg bg-gray-700 hover:bg-gray-600 text-sm font-medium transition"
                >
                  Open Email Client
                </button>
                <button
                  onClick={() => navigator.clipboard.writeText(emailBody)}
                  className="px-4 py-2 rounded-lg bg-gray-800 hover:bg-gray-700 text-sm transition"
                >
                  Copy Body
                </button>
              </div>
            </div>
          </div>

          {/* Preview */}
          {meeting.minutes && (
            <details className="bg-gray-900 rounded-xl border border-gray-800">
              <summary className="px-5 py-3 cursor-pointer text-sm text-gray-400 hover:text-white">
                Preview minutes
              </summary>
              <div className="px-5 pb-5 prose prose-invert prose-sm max-w-none">
                <ReactMarkdown>{meeting.minutes}</ReactMarkdown>
              </div>
            </details>
          )}
        </main>
      </div>
    </>
  );
}
